# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170729_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
