# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170729_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='后端', max_length=20, verbose_name='课程类别'),
        ),
    ]
