# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20170730_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesresource',
            name='download',
            field=models.FileField(max_length=300, upload_to='course/resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
